manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject-rtos
##      revision: v3.1.0       # . . . switching to commit which corrects not-linked RPi Pico bootloader, Zephyr issue #46616:
##      revision: v3.1.0-rc3   # . . . booloader not linked problem appears present in this Zephyr tagged commit - TMH
##      Issue of not linked RPi Pico bootloader reported on 2022-06-15, June 15.
      revision: v3.1.0-rc1
##      revision: main         # . . . pico-sdk appears far incomplete in [zephyr]/modules/hal_rpi_pico
      import: true

    # RaspberryPi Pico SDK, for DMA and SPI driver study . . .
    - name: pico-sdk
      path: pico-sdk
      revision: 1.4.0
      url: https://github.com/raspberrypi/pico-sdk

    # Drivers repository
    - name: zephyr-driver-work-v2
      path: kionix-drivers
      revision: main
      url: https://github.com/tedhavelka/zephyr-driver-work-v2

  self:
    # This repository should be cloned to 
    path: rpi-pico-zephyr-exploration
